[package]
name = "libjitterentropy-sys"
authors.workspace = true
edition.workspace = true
version.workspace = true
license = "MIT"
repository = "https://github.com/thillux/rand_jitterentropy"
description = "provides interface to jitterentropy-library (ffi-bindings)"
keywords = ["rand", "random", "jitterentropy", "rng"]
categories = ["external-ffi-bindings"]
links = "jitterentropy"

[features]
default = []
static = []

[build-dependencies]
bindgen = { workspace = true }
pkg-config = { workspace = true }
