#pragma once

#include <jitterentropy.h>

/*
 * The JENT_MAX_MEMSIZE_* values are defined as function-like macro
 * invocations, which bindgen cannot evaluate. Mirror them into an enum, so
 * that their values end up in the generated bindings. The RUST_ prefix avoids
 * a clash with the macros and is stripped again by build.rs.
 *
 * Which sizes exist depends on the jitterentropy version, hence the guards.
 */
#ifdef JENT_MAX_MEMSIZE_MAX
enum jent_max_memsize {
#ifdef JENT_MAX_MEMSIZE_1kB
	RUST_JENT_MAX_MEMSIZE_1kB = JENT_MAX_MEMSIZE_1kB,
#endif
#ifdef JENT_MAX_MEMSIZE_2kB
	RUST_JENT_MAX_MEMSIZE_2kB = JENT_MAX_MEMSIZE_2kB,
#endif
#ifdef JENT_MAX_MEMSIZE_4kB
	RUST_JENT_MAX_MEMSIZE_4kB = JENT_MAX_MEMSIZE_4kB,
#endif
#ifdef JENT_MAX_MEMSIZE_8kB
	RUST_JENT_MAX_MEMSIZE_8kB = JENT_MAX_MEMSIZE_8kB,
#endif
#ifdef JENT_MAX_MEMSIZE_16kB
	RUST_JENT_MAX_MEMSIZE_16kB = JENT_MAX_MEMSIZE_16kB,
#endif
#ifdef JENT_MAX_MEMSIZE_32kB
	RUST_JENT_MAX_MEMSIZE_32kB = JENT_MAX_MEMSIZE_32kB,
#endif
#ifdef JENT_MAX_MEMSIZE_64kB
	RUST_JENT_MAX_MEMSIZE_64kB = JENT_MAX_MEMSIZE_64kB,
#endif
#ifdef JENT_MAX_MEMSIZE_128kB
	RUST_JENT_MAX_MEMSIZE_128kB = JENT_MAX_MEMSIZE_128kB,
#endif
#ifdef JENT_MAX_MEMSIZE_256kB
	RUST_JENT_MAX_MEMSIZE_256kB = JENT_MAX_MEMSIZE_256kB,
#endif
#ifdef JENT_MAX_MEMSIZE_512kB
	RUST_JENT_MAX_MEMSIZE_512kB = JENT_MAX_MEMSIZE_512kB,
#endif
#ifdef JENT_MAX_MEMSIZE_1MB
	RUST_JENT_MAX_MEMSIZE_1MB = JENT_MAX_MEMSIZE_1MB,
#endif
#ifdef JENT_MAX_MEMSIZE_2MB
	RUST_JENT_MAX_MEMSIZE_2MB = JENT_MAX_MEMSIZE_2MB,
#endif
#ifdef JENT_MAX_MEMSIZE_4MB
	RUST_JENT_MAX_MEMSIZE_4MB = JENT_MAX_MEMSIZE_4MB,
#endif
#ifdef JENT_MAX_MEMSIZE_8MB
	RUST_JENT_MAX_MEMSIZE_8MB = JENT_MAX_MEMSIZE_8MB,
#endif
#ifdef JENT_MAX_MEMSIZE_16MB
	RUST_JENT_MAX_MEMSIZE_16MB = JENT_MAX_MEMSIZE_16MB,
#endif
#ifdef JENT_MAX_MEMSIZE_32MB
	RUST_JENT_MAX_MEMSIZE_32MB = JENT_MAX_MEMSIZE_32MB,
#endif
#ifdef JENT_MAX_MEMSIZE_64MB
	RUST_JENT_MAX_MEMSIZE_64MB = JENT_MAX_MEMSIZE_64MB,
#endif
#ifdef JENT_MAX_MEMSIZE_128MB
	RUST_JENT_MAX_MEMSIZE_128MB = JENT_MAX_MEMSIZE_128MB,
#endif
#ifdef JENT_MAX_MEMSIZE_256MB
	RUST_JENT_MAX_MEMSIZE_256MB = JENT_MAX_MEMSIZE_256MB,
#endif
#ifdef JENT_MAX_MEMSIZE_512MB
	RUST_JENT_MAX_MEMSIZE_512MB = JENT_MAX_MEMSIZE_512MB,
#endif
#ifdef JENT_MAX_MEMSIZE_MAX
	RUST_JENT_MAX_MEMSIZE_MAX = JENT_MAX_MEMSIZE_MAX,
#endif
#ifdef JENT_MAX_MEMSIZE_MASK
	RUST_JENT_MAX_MEMSIZE_MASK = JENT_MAX_MEMSIZE_MASK,
#endif
};
#endif

/*
 * Same for the JENT_HASHLOOP_* values, which were added after jitterentropy
 * 3.7.0.
 */
#ifdef JENT_MAX_HASHLOOP
enum jent_hashloop {
#ifdef JENT_HASHLOOP_1
	RUST_JENT_HASHLOOP_1 = JENT_HASHLOOP_1,
#endif
#ifdef JENT_HASHLOOP_2
	RUST_JENT_HASHLOOP_2 = JENT_HASHLOOP_2,
#endif
#ifdef JENT_HASHLOOP_4
	RUST_JENT_HASHLOOP_4 = JENT_HASHLOOP_4,
#endif
#ifdef JENT_HASHLOOP_8
	RUST_JENT_HASHLOOP_8 = JENT_HASHLOOP_8,
#endif
#ifdef JENT_HASHLOOP_16
	RUST_JENT_HASHLOOP_16 = JENT_HASHLOOP_16,
#endif
#ifdef JENT_HASHLOOP_32
	RUST_JENT_HASHLOOP_32 = JENT_HASHLOOP_32,
#endif
#ifdef JENT_HASHLOOP_64
	RUST_JENT_HASHLOOP_64 = JENT_HASHLOOP_64,
#endif
#ifdef JENT_HASHLOOP_128
	RUST_JENT_HASHLOOP_128 = JENT_HASHLOOP_128,
#endif
#ifdef JENT_MAX_HASHLOOP
	RUST_JENT_MAX_HASHLOOP = JENT_MAX_HASHLOOP,
#endif
#ifdef JENT_MAX_HASHLOOP_MASK
	RUST_JENT_MAX_HASHLOOP_MASK = JENT_MAX_HASHLOOP_MASK,
#endif
};
#endif
