[workspace]
resolver = "2"
members = [
    "linux-crng-ioctl",
    "rand_jitterentropy",
    "libjitterentropy-sys",
    "rngd"
]

[workspace.package]
version = "0.2.0"
authors = ["Markus Theil <theil.markus@gmail.com>"]
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0.102" }
bindgen = { version = "0.72.1", features = ["runtime"] }
clap = { version = "4.5.60", features = ["derive"] }
env_logger = { version = "0.11.9" }
libjitterentropy-sys = { path = "libjitterentropy-sys", version = "0.2.0" }
linux-crng-ioctl = { path = "linux-crng-ioctl", version = "0.2.0" }
log = { version = "0.4.29" }
nix = { version = "0.31.1" }
pkg-config = { version = "0.3.32" }
rand = "0.10.0"
rand_core = "0.10.0"
rand_jitterentropy = { path = "rand_jitterentropy", version = "0.2.0" }
sha3 = { version = "0.11.0-rc.7", features = ["zeroize"] }
syslog = { version = "7.0.0" }
zeroize = { version = "1.8.2", features = ["zeroize_derive"] }

[workspace.lints.clippy]
all = { level = "deny", priority = 0 }
pedantic = { level = "deny", priority = 0 }
cargo = { level = "deny", priority = 0 }
